// Edit all site content here. Replace the sample text, photos and contact details.
const light = "#f2ead8";
export const C = {
  phone: "+91 98855 18959",
  whatsapp: "919885518959",
  email: "hello@heptaconstructions.com",
  address: "Street address, City, State",
  heroImages: ["/hero/h1.jpg", "/hero/h2.jpg", "/hero/h3.jpg"],
  services: [
    { name: "Interior Design", text: "Space planning, 3D visuals and detailed drawings for every room." },
    { name: "Turnkey Interiors", text: "Design, build, furnish and hand over. You get the keys, we do the rest." },
    { name: "Construction", text: "New builds, extensions and structural work by our own site crew." },
    { name: "Renovation", text: "Kitchens, bathrooms or whole homes, planned to keep disruption low." },
    { name: "Custom Furniture", text: "Wardrobes, kitchens and wall units made to your measurements." },
    { name: "Project Management", text: "Already have a design? We run the site, vendors and schedule." },
  ],
  process: [
    ["Consultation", "Site visit, measurements, needs and budget."],
    ["Concept", "Layouts, mood boards and first 3D views."],
    ["Design and quote", "Working drawings, materials and an itemised quote."],
    ["Build", "Our crew builds, with weekly updates and photos."],
    ["Styling", "Furniture, lighting and a snag-list walkthrough."],
    ["Handover", "Keys, warranties and 12 months of free fixes."],
  ],
  stats: [["120+", "Projects delivered"], ["12", "Years of practice"], ["45", "In-house craftsmen"], ["98%", "On-time handover"]],
  // All project text below is SAMPLE content. Gallery paths point at placeholder images in /public.
  projects: [
    {
      slug: "oak-plaster-apartment", href: "/projects/oak-plaster-apartment",
      name: "Oak and Plaster Apartment",
      eyebrow: "Residential", title: "Oak and plaster apartment, opened into one long living space",
      description: "A three-bedroom flat reworked with oak panelling, lime plaster and custom joinery.",
      image: "/work/p1.jpg", imageAlt: "Apartment living room", background: "#1e3a8a", foreground: light,
      location: "City, State", area: "1,850 sq ft", year: "2025", duration: "16 weeks",
      overview: "The owners wanted a calm, bright home for a family of four. We merged the living, dining and kitchen areas into one long space and warmed it up with natural materials.",
      challenge: "The original layout had three small rooms with load-bearing walls between them, and very little daylight reached the middle of the flat.",
      approach: "Our structural engineer approved a steel beam to open the walls. We then planned lighting, joinery and finishes together so the new space felt designed as one piece.",
      scope: ["Space planning", "Full interior design", "Structural opening", "Custom joinery", "Electrical and lighting", "Lime plaster finishes"],
      materials: ["Natural oak veneer", "Lime plaster", "Honed stone flooring", "Brass fittings"],
      results: [["16 wks", "Start to handover"], ["0", "Change orders after sign-off"], ["3", "Rooms merged into one"]],
      gallery: ["/work/p2.jpg", "/hero/h1.jpg", "/work/p3.jpg"],
    },
    {
      slug: "studio-office-floor", href: "/projects/studio-office-floor",
      name: "Studio Office Floor",
      eyebrow: "Commercial", title: "A studio office floor built for focus and meetings",
      description: "Open workspace with acoustic ceilings, concrete-finish floors and glass meeting rooms.",
      image: "/work/p2.jpg", imageAlt: "Office interior", background: "#5b1a2e", foreground: light,
      location: "City, State", area: "6,200 sq ft", year: "2025", duration: "11 weeks",
      overview: "A growing design team needed one floor that worked for quiet focus, loud collaboration and client visits, all built while the rest of the building stayed open.",
      challenge: "The shell had low ceilings, noisy neighbours and a tight eleven-week window before the lease on their old office ended.",
      approach: "We prefabricated partitions and joinery in our workshop, built after hours, and used acoustic ceiling baffles to keep the open plan quiet.",
      scope: ["Layout and design", "Partitions and glazing", "Acoustic ceilings", "Flooring", "Electrical and data", "Furniture supply"],
      materials: ["Concrete-finish microtopping", "Acoustic baffles", "Toughened glass", "Powder-coated steel"],
      results: [["11 wks", "Start to handover"], ["120", "Workstations delivered"], ["After hours", "Noisy work scheduled"]],
      gallery: ["/work/p1.jpg", "/hero/h2.jpg", "/work/p4.jpg"],
    },
    {
      slug: "courtyard-villa", href: "/projects/courtyard-villa",
      name: "Courtyard Villa",
      eyebrow: "Construction", title: "A courtyard villa, from foundation to final finish",
      description: "A two-storey home around a central courtyard, built with local stone and deep verandas.",
      image: "/work/p3.jpg", imageAlt: "Villa exterior", background: "#14506b", foreground: light,
      location: "City, State", area: "4,200 sq ft", year: "2024", duration: "11 months",
      overview: "A joint family wanted a home where everyone could live together without living on top of each other, organised around a shaded central courtyard.",
      challenge: "A sloping plot, a monsoon in the middle of the foundation stage and a family who wanted regular site visits.",
      approach: "We phased the build around the weather, held fortnightly site walks with the family, and used local stone to keep the house cool and the costs predictable.",
      scope: ["Architecture and structure", "Civil work", "Plumbing and electrical", "Interiors", "Landscaping"],
      materials: ["Local stone", "Reinforced concrete", "Clay roof tiles", "Teak windows"],
      results: [["11 mo", "Foundation to move-in"], ["2", "Storeys around one courtyard"], ["Fortnightly", "Family site walks"]],
      gallery: ["/work/p4.jpg", "/hero/h3.jpg", "/work/p1.jpg"],
    },
    {
      slug: "cafe-and-lounge", href: "/projects/cafe-and-lounge",
      name: "Cafe and Lounge",
      eyebrow: "Hospitality", title: "A cafe and lounge with lighting that follows the day",
      description: "Layered seating zones, a live-edge counter and warm evening lighting.",
      image: "/work/p4.jpg", imageAlt: "Cafe interior", background: "#3b2a6e", foreground: light,
      location: "City, State", area: "2,400 sq ft", year: "2026", duration: "9 weeks",
      overview: "The brief was a cafe that works for morning laptops and evening dinners. We split the room into distinct seating zones and let the lighting change the mood through the day.",
      challenge: "A single long room with a fixed kitchen position, and an opening date tied to a festival weekend.",
      approach: "We zoned the space with level changes and joinery instead of walls, programmed lighting scenes for morning, afternoon and evening, and built the counter in our workshop in parallel with the site work.",
      scope: ["Concept and layout", "Counter and joinery", "Lighting design", "Kitchen coordination", "Furniture and styling"],
      materials: ["Live-edge timber", "Terrazzo", "Warm LED lighting", "Boucle upholstery"],
      results: [["9 wks", "Start to opening"], ["3", "Lighting scenes through the day"], ["On time", "Ready for festival weekend"]],
      gallery: ["/work/p3.jpg", "/hero/h1.jpg", "/work/p2.jpg"],
    },
  ],
  testimonials: [
    { quote: "They finished a week early and kept the site clean every evening. The result looks exactly like the render.", name: "Client name", project: "Apartment interior (sample)" },
    { quote: "One team for design and construction meant no finger pointing. We always knew who to call.", name: "Client name", project: "Office fit-out (sample)" },
    { quote: "The quote was itemised and the final bill matched it. That alone made us trust them.", name: "Client name", project: "Villa construction (sample)" },
  ],
};
